blog-2002/apps/views/main.py
from flask import Blueprint,render_template,flash,redirect,url_for,request,current_app,abort
from apps.models import Posts
from apps.forms import PostsForm
from flask_login import login_required,current_user
from apps.exts import db
main = Blueprint("main",__name__)



@main.route('/',methods=['GET','POST'])
# @login_required
def index():
    form = PostsForm()
    if form.validate():
        #判断是否登录了
        if current_user.is_authenticated:
            #获取当前登录的用户
            u = current_user._get_current_object()
            p = Posts(content=form.content.data,author=u)
            db.session.add(p)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            flash('登录以后才可以发表')
            return redirect(url_for('users.login'))

    #读取所有的博客
    # posts = Posts.query.filter_by(rid=0).all()
    # return render_template('main/index.html',form=form,posts=posts)
    #接收用户想查看第几页
    #http://www.baidu.com/?p=1 如果不写p参数 默认为1 类型必须是int 类型
    page = request.args.get('p',1,type=int)
    #拿到分页对象
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.pub_time.desc()).paginate(page,per_page=current_app.config['PAGE_COUNT'],error_out=False)
    posts = pagination.items
    return render_template('main/index.html',form=form,posts=posts,pagination=pagination)

@main.route('/detail/<postid>/')
def post_detail(postid):
    post = Posts.query.get(postid)
    if not post:  #如果没有帖子详情 那么我们就抛出404错误
        abort(404)

    #查询帖子的评论内容
    comments = Posts.query.filter_by(rid=postid).order_by(Posts.pub_time.desc()).all()
    return render_template('main/detail.html',post=post,comments=comments)

blog-2002/apps/views/posts.py
from flask import Blueprint,render_template,jsonify
from .decorators import login_requireds
from flask_login import current_user


posts = Blueprint("posts",__name__)


# 用来处理收藏和取消收藏
@posts.route('/collect/<pid>/')
# @login_requireds
def collect(pid):
    #原来收藏  点击 变成 取消收藏
    if current_user.is_favorite(pid):
        current_user.del_favorite(pid)
    else:
        current_user.add_favorite(pid)
    return jsonify({'result':'ok'})
    #异步操作   #多件事情 一起做
    #点击收藏
    #收藏

    #没收藏    点击 收藏

    # 用户  收藏

    # 用户 取消收藏

    # 判断是否收藏

blog-2002/apps/templates/main/detail.html
{% extends 'common/base.html' %}
{% from 'common/macro/macro.html' import pagination_show%}

{% block title %}
    {{ post.content }}
{% endblock %}



{% block content %}
    {% block page_content %}
            {{ post.author.username }}/{{ moment(post.pub_time).fromNow() }}
    {% endblock %}

{% endblock %}

blog-2002/apps/templates/main/index.html
{% extends 'common/base.html' %}
{% from 'common/macro/macro.html' import pagination_show%}

{% block title %}
    博客首页
{% endblock %}



{% block content %}
    {% block page_content %}
        {{ wtf.quick_form(form) }}

        {% for p in posts %}
            <div class="media">
                <div class="media-left">
{#                    http://baidu.com/postdetail/2/#}
                    <a href="{{ url_for('main.post_detail',postid=p.id) }}">
                        <img class="media-object" src="{{ url_for('static',filename='uploads/'+p.author.icon) }}"
                             alt="头像">
                    </a>
                </div>
                <div class="media-body">
                    <div style="float: right">{{ moment(p.pub_time).fromNow() }}</div>
                    <h4 class="media-heading">{{ p.author.username }}</h4>
                    {{ p.content }}
                    {% if current_user.is_authenticated  %}
                          <div url="{{ url_for('posts.collect',pid=p.id) }}" style="cursor: pointer" class="collect">
                              {{ current_user.is_favorite(p.id) }}
                              {% if current_user.is_favorite(p.id) %}
                                取消收藏
                            {% else %}
                                收藏
                            {% endif %}
                    </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}

    {% endblock %}

    {{ pagination_show(pagination,'main.index') }}
{% endblock %}

{% block scripts %}
 {{ super() }}
    <script type="text/javascript">
        $(function () {
            $(".collect").click(function () {
                _this = this
                {#alert($(this).attr('url'))#}
                $.get($(this).attr('url'), function(data){
                    if(data['result'] == 'ok'){
                         if($(_this).text() == '收藏'){
                            $(_this).text('取消收藏')
                        }else{
                            $(_this).text('收藏')
                        }
                    }
                });
            })
        })
    </script>
{% endblock %}